### ISSUE TITLE
Custom Head's

### ISSUE THREAD

**Issue by Sivochek** [nulli0n/GoldenCrates#41]
So, I have a custom head I added into the golden crates as the item that you open the crate with it works but after a restart, it just makes it a steve head.

**Comment by nulli0n** [comment]
should be fixed now

**Comment by Dark3581** [comment]
> 
> 
> should be fixed now

Still having the same issue unless you haven't updated the jar

**Comment by nulli0n** [comment]
Fixed.
